Fix race condition in `MiniScheduler::Manager`
The runner keep alive thread may call `MiniScheduler::Manager#keep_alive` before
the `@runner` instance variable has been assigned in
`MiniScheduler::Manager#initialize`. Since
`MiniScheduler::Manager#keep_alive` expects the `@runner` instance
variable to not be `nil`, an error ends up being raised.

```
Failure/Error: ids = [identity_key, *@runner.worker_thread_ids] if ids.size == 0

NoMethodError:
  undefined method `worker_thread_ids' for nil

/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/mini_scheduler-0.18.0/lib/mini_scheduler/manager.rb:360:in `keep_alive'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/mini_scheduler-0.18.0/lib/mini_scheduler/manager.rb:40:in `keep_alive'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/mini_scheduler-0.18.0/lib/mini_scheduler/manager.rb:31:in `block (2 levels) in initialize'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/mini_scheduler-0.18.0/lib/mini_scheduler/manager.rb:31:in `synchronize'
/var/www/discourse/vendor/bundle/ruby/3.3.0/gems/mini_scheduler-0.18.0/lib/mini_scheduler/manager.rb:31:in `block in initialize'
```